### ISSUE TITLE
UniqueIdProperty Django Form

### ISSUE THREAD

**Issue by Ramel** [neo4j-contrib/neomodel#444] opened 2019-04-26 15:38 UTC
Hello,

I'm trying to do a Django Form to edit a Neo4j previously created database.
In Django I've created a :

```
class Person(DjangoNode):
   uid = UniqueIdProperty()
   name = StringProperty()
```

and in my Form, i call **uid**, but each time i refresh the Form, the **uid** it changes.

I've done the:

`python manage.py install_labels`

But I don't understand why the **uid** is modified each time I reload the Form?

Thanks in advance,

Ramel

**Comment by aanastasiou** [comment] 2019-04-26 16:23
@Ramel Can you make the question a bit more specific to `neomodel` please?

**Comment by Ramel** [comment] 2019-04-26 19:49
Is the uid (UniqueIdProperty) generated when I create a new node in the database and added to it or exists only in neomodel? The uid seems to be fixed if I edit with the form a value for a node. Otherwise it's change each time I reload the form.
But perhaps the question is more neo4j-contrib/django-neomodel centric.

**Comment by aanastasiou** [comment] 2019-04-27 18:11
@Ramel Correct. The `UniqueIdProperty` originates in `neomodel` and yes, the behaviour you describe is consistent with creating new nodes or editing existing nodes.

Beyond this, it is difficult to comment on what may be causing this behaviour in your app without a quick glance at the code (?).

Not sure I can see a "problem" here however. We can keep chatting here if it might help you but I will be closing the "issue" for the moment.

All the best

**Closed by aanastasiou** 2019-04-27 18:11 UTC

**Comment by Ramel** [comment] 2019-04-29 12:28
I've make a repo for testing purpose:

https://github.com/Ramel/test-django-neomodel

I'm using the `:play movies` database and Django Neomodel. In the Person db there is a 'handle_uid', but I do not use it in this example.

So I create an "uid" UniqueIdProperty() in the DjangoNode model. And call the node by this "uid" in the form, because it's my entry point for the data, the name for example. And each time I reload the master form for editing a Node, the "uid" change. Should I save, the 'uid" value for each Node when I start the Django instance, but how, or use an already filled one like 'handle_uid'? Or I certainly miss something :-)

Thanks in advance.

**Comment by aanastasiou** [comment] 2019-04-30 08:43
@Ramel I am guessing that the problem is caused [here](https://github.com/Ramel/test-django-neomodel/blob/ad02389792f1c6578301f25425ca8c1f1ccaf49b/testDjangoNeomodel/neo4j_api/views.py#L54) (?). 

What is the value of `uid` that you pass to that form when no `uid` is provided (?) (i.e. as a response to a simple `GET`).

**Comment by Ramel** [comment] 2019-04-30 10:13
The value of the "uid" seems randomly generated each time I load the form. The Form return an uid, different each time I reload the Form. As the uid is not fixed/saved? for that node in neomodel?

I've make another branch (handle_id) in the repo where I use the already existent "handle_id" as PK and the form works perfectly.
My error, I think, is to expect that neomodel generate an "uid" and keep it for the given node. I've expected that the django-neomodel  'install_labels' is there for that purpose.

So, either I generate all the database nodes with a unique "handle_id". Or without modifying the database, I use an UniqueIdProperty, but it seems it needs to be applied (saved?) to the node before use, it's here I'm stalled with UniqueIdProperty.

**Comment by Ramel** [comment] 2019-04-30 14:31
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from neo4j_api import models
>>> from neomodel import config
>>> config.DATABASE_URL = 'bolt://neo4j:password@localhost:7687'
>>> from neo4j_api.models import Person
>>> someone = Person.nodes.get_or_none(name='Keanu Reeves')
>>> print(someone)
{'uid': 'ca7b73ee18d442e0ab353d28262f15ff', 'name': 'Keanu Reeves', 'id': 1}
>>> print(someone)
{'uid': 'ca7b73ee18d442e0ab353d28262f15ff', 'name': 'Keanu Reeves', 'id': 1}
>>> someone = Person.nodes.get_or_none(uid='ca7b73ee18d442e0ab353d28262f15ff')
>>> print(someone)
None
>>> someone = Person.nodes.get_or_none(name='Keanu Reeves')
>>> print(someone)
{'uid': '791cc294db5245d9981ce38c87af6e55', 'name': 'Keanu Reeves', 'id': 1}
>>> print(someone)
{'uid': '791cc294db5245d9981ce38c87af6e55', 'name': 'Keanu Reeves', 'id': 1}
>>> someone = Person.nodes.get_or_none(uid='791cc294db5245d9981ce38c87af6e55')
>>> print(someone)
None
>>> someone = Person.nodes.get_or_none(name='Keanu Reeves')
>>> print(someone)
{'uid': '9ce7492be1034c53bec5dbfa5bb6f392', 'name': 'Keanu Reeves', 'id': 1}
>>>
```
@aanastasiou Is that related?

**Comment by aanastasiou** [comment] 2019-05-01 20:30
@Ramel OK, let me see if I get this straight. This is an already populated database and you have built a model that **matches the node structure and relationships** (?). With these, you can retrieve a `Person` (?) by name but when you try to retrieve them by `uid`, they are reported as inexistent (?). The second time you try to retrieve by name, their uid appears to have changed.

Do the nodes that you have in the database **already contain** the `uid` attribute or is this something you added to the model and you expect it to work *out of the box without any modifications* (?). My gut feeling tells me that the `Person` in the database do not have a populated `uid` attribute and what you get when you "refresh" the node is the default behaviour of the `UniqueIdProperty`.

The `install_labels` does not affect (and is not affected) by attributes at all.

To get the behaviour you expect, do something like: `list([a_node.save() for a_node in Person.nodes.all()])` at least once. That is to try and write the generated `uid`'s back in to the database so that the `uid` gets populated and is not re-generated at each call. This `list(....` business above might not work exactly as I am writing it here because I cannot exactly test it where I am right now, but the main idea is to populated the `uid` before you have to use it. And the even more main idea is that **the schema in the database must much the models and be confirmed by the data**. That is the whole point of [MDE](https://en.wikipedia.org/wiki/Model-driven_engineering).

Hope this helps (?).

**Comment by Ramel** [comment] 2019-05-02 10:04
That's correct. If I save the *uid* into the Person nodes, with  ```list([a_node.save() for a_node in Person.nodes.all()])```, then I can retrieve the Persons by their *uid*.
My mistake was to think that neomodel was able to generate an *uid* UniqueIdproperty. That's the case, but it doesn't save it if we not tell him to do it. In my case, working with an already existent database, without any *uid* for each Node, I should add/generate one and save it on each Node, before using it.
Problem solved. Thanks a lot for your time and explanations.

**Comment by aanastasiou** [comment] 2019-05-02 11:41
@Ramel No worries, glad you got it sorted out in the end.

A few clarifications:

> My mistake was to think that neomodel was able to generate an `uid UniqueIdproperty`. That's the case, but it doesn't save it if we not tell him to do it. 

Indeed.

`neomodel` will (try to) make your life easier when interfacing with a Neo4j database but it will not take "major" decisions for you. In this case, adding the attribute to the node (one operation) and then populating it with the valid values (another operation).

Yes, the property does generate a value as part of its normal functionality but writing it back to the database happens via the "Update" operation on the node. To create a node you just create a `StructuredNode` descendant and call its `save()`. To *update* the node, **it must first have been saved** and then simply edit the attribute you wish to edit and call `save()` on it again. `neomodel` then detects that this is an operation on an already saved node and proceeds with an update. For more information please see [here](https://neomodel.readthedocs.io/en/latest/getting_started.html#create-update-delete).

All the best
