### ISSUE TITLE
Explicit closing of the driver

### ISSUE THREAD

**Issue by dzianis-hrynko** [neo4j-contrib/neomodel#697] opened 2023-04-25 12:20 UTC
## Expected Behavior (Mandatory)
Saving prepared entity without any exceptions

## Actual Behavior (Mandatory)
Entities have been saved in DB, however the exceptions has thrown

`
Exception ignored in: <function Driver.__del__ at 0x7f1fe649e440>
Traceback (most recent call last):
  File ".local/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 411, in __del__
  File ".local/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 456, in close
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 367, in close
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 320, in _close_connections
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 757, in close
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 609, in _send_all
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_common.py", line 145, in flush
  File ".local/lib/python3.10/site-packages/neo4j/_async_compat/util.py", line 113, in callback
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 688, in _set_defunct_write
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 691, in _set_defunct
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Bolt.__del__ at 0x7f1fe64679a0>
Traceback (most recent call last):
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 161, in __del__
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 757, in close
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 609, in _send_all
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_common.py", line 145, in flush
  File ".local/lib/python3.10/site-packages/neo4j/_async_compat/util.py", line 113, in callback
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 688, in _set_defunct_write
  File ".local/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 691, in _set_defunct
ImportError: sys.meta_path is None, Python is likely shutting down

Process finished with exit code 0
`
## How to Reproduce the Problem
I use an example of the code from documentation
https://neomodel.readthedocs.io/en/latest/getting_started.html

### Simple Example

`
from neomodel import (config, StructuredNode, StringProperty, IntegerProperty,
                      UniqueIdProperty)

user = 'your-user'
psw = 'your-pass'
uri = 'your-db-id.databases.neo4j.io'

config.DATABASE_URL = 'neo4j+s://{}:{}@{}'.format(user, psw, uri)

class Person(StructuredNode):
    uid = UniqueIdProperty()
    name = StringProperty(unique_index=True)
    age = IntegerProperty(index=True, default=0)

if __name__ == "__main__":
    jim = Person(name='Jisdrm', age=3).save()  # Create
    jim.name = "adasd"
    jim.save()  # Update, (with validation)

`

## Screenshots (where it's possibile)
![image](https://user-images.githubusercontent.com/55101692/234274537-8eef3e8d-dd50-47aa-abc4-7fabec9eb68d.png)

## Specifications (Mandatory)

5.0.0 

### Versions

  - OS: Ubuntu
  - Library: python 3.10
  - Neo4j: 5.7.0

**Comment by aanastasiou** [comment] 2023-04-25 13:32
@dzianis-hrynko Thanks for raising this with us 

To my understanding this is an exception that was thrown at the level of the [neo4j python3 driver](https://neo4j.com/docs/api/python-driver/current/) rather than the level of `neomodel` (or as a result of a `neomodel` call).

Most probably because your program run very fast locally and exited before the driver had finished its own "destruction". Can you please share a bit more of your code from `if __name__ == "__main__":` onwards?

Also, **please refrain from posting credentials and full URLs in the future** when posting examples such as this. The usernames, passwords and connection URL are not important to understand what the issue is about here.

**Comment by dzianis-hrynko** [comment] 2023-04-25 16:15
@aanastasiou 

> Can you please share a bit more of your code from if __name__ == "__main__": onwards?

That's all I have in `if __name__ == "__main__":`
![image](https://user-images.githubusercontent.com/55101692/234339046-1d5a1ec7-8914-4ee9-887d-94e5e769bd1b.png)

I've tested how neomodel works to choose neomodel or just python driver use in my projects and faced with that issues.


>Most probably because your program run very fast locally and exited before the driver had finished its own "destruction". 
It's weird.
Anyway, I've added sleep after saving to give time to destruct, and the exception is the same.

Maybe there is another way to solve the issues? I'm not sure if it's possible to destruct the driver forcibly

**Comment by mariusconjeaud** [comment] 2023-07-19 14:20
Hello @dzianis-hrynko can you with release [5.1.0](https://pypi.org/project/neomodel/) ? It updates the driver to latest 5.10

**Comment by navindev26** [comment] 2023-08-02 00:45
I had the same issue when using Neo4jGraph via LangChain. The script seems to finish before the database driver completes its cleanup. Fixed it by calling close() explicitly at the end of

`if __name__ == "__main__":`

```
uri = "neo4j://example.com:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "password"))
driver.close()  # close the driver object.
```


forLlangChain using the wrapper `Neo4jGraph` it was
`neo_graph._driver.close() `

**Comment by mariusconjeaud** [comment] 2023-08-02 08:02
This is a general issue that we are facing and thinking about, because until version 5.x of the Neo4j Python driver, it would close itself, but it is now deprecated in version 5.x
This means we get quite a few deprecation warnings when running the tests about this.

I just couldn't figure out the best place to explicitly close the driver yet though. Maybe the solution lies in providing a method to call to the users, so that they can close the driver at the end of their app's lifecycle.
It would also become irrelevant if we move the driver creation out of neomodel and into the user's hands as the other OGMs do (like SDN) ; then the lifecycle of the driver is managed by the app and not the library, which makes more sense.

So i'm keeping this open but renaming it to something more general.

**Closed** 2023-08-02 10:00 UTC
Labels: deprecation
