### ISSUE TITLE
4.0.9 release

### ISSUE THREAD

**Issue by olegchigirin** [neo4j-contrib/neomodel#643] opened 2022-09-19 11:07 UTC
Question only.

In the master branch there are several major and important updates, that are not yet released:

https://github.com/neo4j-contrib/neomodel/pull/604
https://github.com/neo4j-contrib/neomodel/pull/607
https://github.com/neo4j-contrib/neomodel/pull/601

And several more.

When we can expect the release of a new version of neomodel?

**Comment by mariusconjeaud** [comment] 2023-02-01 10:11
Duplicate of #653

**Comment by mariusconjeaud** [comment] 2023-02-01 10:11
Closing to group all discussions about the evolution of neomodel in #653

**Closed by mariusconjeaud** 2023-02-01 10:11 UTC
