### ISSUE TITLE
Can't connect to other databases other than the default one. 

### ISSUE THREAD

**Issue by josewails** [neo4j-contrib/neomodel#563] opened 2021-06-29 12:03 UTC
What's the best way to connect to a different database other than the default one. 

Looking at:
 https://github.com/neo4j-contrib/neomodel/blob/9c405aa5b75cbf3e2612ba0605b25996ba607e2d/neomodel/util.py#L98
  It looks like `bolt://neo4j:password@localhost:7687/test` should connect to a database named test. However, this doesn't work. Am I missing something?

**Comment by alexlitvinenko** [comment] 2021-07-02 07:08
Duplicate of #541

**Closed** 2023-09-26 13:12 UTC
