### ISSUE TITLE
Transaction hangs when calling  a custom method on a SemiStructuredNode

### ISSUE THREAD

**Issue by Moro-Code** [neo4j-contrib/neomodel#448] opened 2019-05-12 17:51 UTC
Hello,

I am experiencing this very strange issue and I'm not sure as to whether it something I am doing. I have the following model.

```python 
from neomodel.contrib import SemiStructuredNode
from neomodel import(
    StringProperty,
    UniqueIdProperty,
    IntegerProperty,
    DateTimeProperty,
    BooleanProperty
)
from typing import Optional
from datetime import datetime
import pytz
from .utils.sentimentSetter import SentimentSetter
class ConductedSurvey(SemiStructuredNode):

    nodeId = UniqueIdProperty()
    addedOn = DateTimeProperty(default_now=True)
    updatedOn = DateTimeProperty()
    status = StringProperty(
                            default="active", 
                            choices={
                                "closed": "closed",
                                "active": "active",
                                "abandoned": "abandoned"
                                }
                            )
    sentimentSet = BooleanProperty(default= False)
    def pre_save(self):
        if self.updatedOn is None:
            self.updatedOn = self.addedOn
        else:
            self.updatedOn = datetime.utcnow().replace(tzinfo=pytz.utc)
        if self.sentimentSet is False:
            SentimentSetter.setSentimentVariables(self)

    def set_closedOn(self, dt: Optional[datetime] = None) -> None:
        if dt is None:
            self.closedOn = datetime.utcnow().replace(tzinfo=pytz.utc)
        else:
            self.closedOn = dt.replace(tzinfo=pytz.utc)
```

I am running the following test

```python
def test_setClosedOn_method(self):
        with self.app.app_context():
            from src.database.db import get_db
            from src.models.conducted_survey_model import ConductedSurvey

            current_transaction = get_db().transaction
            test_conducted_survey_3 = ConductedSurvey()
            test_conducted_survey_3.set_closedOn()
            with current_transaction:
                test_conducted_survey_3.save()
            
            assert test_conducted_survey_3.closedOn is not None
            assert isinstance(test_conducted_survey_3, datetime)

            set_to_date = datetime(2019,4,21,15,6,9)

            with current_transaction:
                test_conducted_survey_3.set_closedOn(set_to_date)
                test_conducted_survey_3.save()
            
            assert test_conducted_survey_3.closedOn == set_to_date
```
Whenever this test is run the transaction never completes. When I comment out the line
```python
test_conducted_survey_3.set_closedOn()
```
the transaction completes and the node is saved. 

Here is some relevant  information
python: 3.7.3
neomodel: 3.3.1
Neo4J: 3.5.3 Enterprise
Platform: MacOs Mojave

What am I doing wrong here? 

Edit:

 It seems that if I call the save method before I call my method it works i.e.

```python 

with current_transaction:
     test_conducted_survey_3 = ConductedSurvey()
     test_conducted_survey_3.save()
     test_conducted_survey_3.set_closedOn()
     test_conducted_survey_3.save()
```

Edit:

This seems to be an issue with setting an ad-hoc datetime field

See the following error traceback 
``` bashself = <neomodel.match.NodeSet object at 0x111ba04a8>, lazy = False

    def all(self, lazy=False):
        """
        Return all nodes belonging to the set
        :param lazy: False by default, specify True to get nodes with id only without the parameters.
        :return: list of nodes
        :rtype: list
        """
>       return self.query_cls(self).build_ast()._execute(lazy)

../../venv/lib/python3.7/site-packages/neomodel/match.py:472: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neomodel.match.QueryBuilder object at 0x111ba0828>, lazy = False

    def _execute(self, lazy=False):
        if lazy:
            # inject id = into ast
            self._ast['return'] = 'id({})'.format(self._ast['return'])
        query = self.build_query()
>       results, _ = db.cypher_query(query, self._query_params, resolve_objects=True)

../../venv/lib/python3.7/site-packages/neomodel/match.py:447: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neomodel.util.Database object at 0x10fcda108>, args = (' MATCH ((conductedsurvey:ConductedSurvey)) RETURN conductedsurvey', {}), kwargs = {'resolve_objects': True}
_db = <neomodel.util.Database object at 0x10fcda108>

    def wrapper(self, *args, **kwargs):
        # Sort out where to find url
        if hasattr(self, 'db'):
            _db = self.db
        else:
            _db = self
    
        if not _db.url:
            _db.set_connection(config.DATABASE_URL)
>       return func(self, *args, **kwargs)

../../venv/lib/python3.7/site-packages/neomodel/util.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neomodel.util.Database object at 0x10fcda108>, query = ' MATCH ((conductedsurvey:ConductedSurvey)) RETURN conductedsurvey', params = {}, handle_unique = True, retry_on_session_expire = False
resolve_objects = True

    @ensure_connection
    def cypher_query(self, query, params=None, handle_unique=True, retry_on_session_expire=False, resolve_objects=False):
        """
        Runs a query on the database and returns a list of results and their headers.
    
        :param query: A CYPHER query
        :type: str
        :param params: Dictionary of parameters
        :type: dict
        :param handle_unique: Whether or not to raise UniqueProperty exception on Cypher's ConstraintValidation errors
        :type: bool
        :param retry_on_session_expire: Whether or not to attempt the same query again if the transaction has expired
        :type: bool
        :param resolve_objects: Whether to attempt to resolve the returned nodes to data model objects automatically
        :type: bool
        """
    
        if self._pid != os.getpid():
            self.set_connection(self.url)
    
        if self._active_transaction:
            session = self._active_transaction
        else:
            session = self.driver.session()
    
        try:
            # Retrieve the data
            start = time.time()
            response = session.run(query, params)
>           results, meta = [list(r.values()) for r in response], response.keys()

../../venv/lib/python3.7/site-packages/neomodel/util.py:212: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <generator object StatementResult.records at 0x111aed480>

>   results, meta = [list(r.values()) for r in response], response.keys()

../../venv/lib/python3.7/site-packages/neomodel/util.py:212: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neo4j.v1.result.BoltStatementResult object at 0x111ba0518>

    def records(self):
        """ Generator for records obtained from this result.
    
        :yields: iterable of :class:`.Record` objects
        """
        records = self._records
        next_record = records.popleft
        while records:
            yield next_record()
        attached = self.attached
        if attached():
            self._session.send()
        while attached():
>           self._session.fetch()

../../venv/lib/python3.7/site-packages/neo4j/v1/api.py:729: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neo4j.v1.api.Session object at 0x111b31f60>

    def fetch(self):
        """ Attempt to fetch at least one more record.
    
        :returns: number of records fetched
        """
        if self._connection:
>           detail_count, _ = self._connection.fetch()

../../venv/lib/python3.7/site-packages/neo4j/v1/api.py:340: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neo4j.bolt.connection.Connection object at 0x111b08e80>

    def fetch(self):
        try:
>           return self._fetch()

../../venv/lib/python3.7/site-packages/neo4j/bolt/connection.py:287: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neo4j.bolt.connection.Connection object at 0x111b08e80>

    def _fetch(self):
        """ Receive at least one message from the server, if available.
    
        :return: 2-tuple of number of detail messages and number of summary messages fetched
        """
        if self.closed():
            raise self.Error("Failed to read from closed connection {!r}".format(self.server.address))
        if self.defunct():
            raise self.Error("Failed to read from defunct connection {!r}".format(self.server.address))
        if not self.responses:
            return 0, 0
    
        self._receive()
    
        details, summary_signature, summary_metadata = self._unpack()
    
        if details:
            log_debug("S: RECORD * %d", len(details))  # TODO
>           self.responses[0].on_records(details)

../../venv/lib/python3.7/site-packages/neo4j/bolt/connection.py:310: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

records = [[Structure<b'N'>(53, ['ConductedSurvey'], {'sentimentCalculated': False, 'closedOn': Structure<b'f'>(1557688852, 7488...sentimentSet': True, 'nodeId': 'e398bbb096864a49913b42f968d596ba', 'addedOn': 1557688852.653614, 'status': 'active'})]]

    def on_records(records):
        # Called on receipt of one or more result records.
>       self._records.extend(map(lambda record: self.zipper(self.keys(), self._hydrant.hydrate(record)), records))

../../venv/lib/python3.7/site-packages/neo4j/v1/result.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

record = [Structure<b'N'>(53, ['ConductedSurvey'], {'sentimentCalculated': False, 'closedOn': Structure<b'f'>(1557688852, 74880...'sentimentSet': True, 'nodeId': '4ade1c3f52554304a3e5b2e075b36523', 'addedOn': 1557688852.565278, 'status': 'active'})]

>   self._records.extend(map(lambda record: self.zipper(self.keys(), self._hydrant.hydrate(record)), records))

../../venv/lib/python3.7/site-packages/neo4j/v1/result.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neo4j.v1.types.PackStreamHydrator object at 0x111ba0a90>
values = [Structure<b'N'>(53, ['ConductedSurvey'], {'sentimentCalculated': False, 'closedOn': Structure<b'f'>(1557688852, 74880...'sentimentSet': True, 'nodeId': '4ade1c3f52554304a3e5b2e075b36523', 'addedOn': 1557688852.565278, 'status': 'active'})]

    def hydrate(self, values):
        """ Convert PackStream values into native values.
        """
    
        def hydrate_(obj):
            if isinstance(obj, Structure):
                try:
                    f = self.hydration_functions[obj.tag]
                except KeyError:
                    # If we don't recognise the structure type, just return it as-is
                    return obj
                else:
                    return f(*map(hydrate_, obj.fields))
            elif isinstance(obj, list):
                return list(map(hydrate_, obj))
            elif isinstance(obj, dict):
                return {key: hydrate_(value) for key, value in obj.items()}
            else:
                return obj
    
>       return tuple(map(hydrate_, values))

../../venv/lib/python3.7/site-packages/neo4j/v1/types/__init__.py:270: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = Structure<b'N'>(53, ['ConductedSurvey'], {'sentimentCalculated': False, 'closedOn': Structure<b'f'>(1557688852, 748800... 'sentimentSet': True, 'nodeId': '4ade1c3f52554304a3e5b2e075b36523', 'addedOn': 1557688852.565278, 'status': 'active'})

    def hydrate_(obj):
        if isinstance(obj, Structure):
            try:
                f = self.hydration_functions[obj.tag]
            except KeyError:
                # If we don't recognise the structure type, just return it as-is
                return obj
            else:
>               return f(*map(hydrate_, obj.fields))

../../venv/lib/python3.7/site-packages/neo4j/v1/types/__init__.py:262: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = {'addedOn': 1557688852.565278, 'closedOn': Structure<b'f'>(1557688852, 748800999, 'UTC'), 'id': 53, 'nodeId': '4ade1c3f52554304a3e5b2e075b36523', ...}

    def hydrate_(obj):
        if isinstance(obj, Structure):
            try:
                f = self.hydration_functions[obj.tag]
            except KeyError:
                # If we don't recognise the structure type, just return it as-is
                return obj
            else:
                return f(*map(hydrate_, obj.fields))
        elif isinstance(obj, list):
            return list(map(hydrate_, obj))
        elif isinstance(obj, dict):
>           return {key: hydrate_(value) for key, value in obj.items()}

../../venv/lib/python3.7/site-packages/neo4j/v1/types/__init__.py:266: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <dict_itemiterator object at 0x111b29b38>

>   return {key: hydrate_(value) for key, value in obj.items()}

../../venv/lib/python3.7/site-packages/neo4j/v1/types/__init__.py:266: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = Structure<b'f'>(1557688852, 748800999, 'UTC')

    def hydrate_(obj):
        if isinstance(obj, Structure):
            try:
                f = self.hydration_functions[obj.tag]
            except KeyError:
                # If we don't recognise the structure type, just return it as-is
                return obj
            else:
>               return f(*map(hydrate_, obj.fields))

../../venv/lib/python3.7/site-packages/neo4j/v1/types/__init__.py:262: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

seconds = 52.748800999, nanoseconds = 748800999, tz = 'UTC'

    def hydrate_datetime(seconds, nanoseconds, tz=None):
        """ Hydrator for `DateTime` and `LocalDateTime` values.
    
        :param seconds:
        :param nanoseconds:
        :param tz:
        :return: datetime
        """
        minutes, seconds = map(int, divmod(seconds, 60))
        hours, minutes = map(int, divmod(minutes, 60))
        days, hours = map(int, divmod(hours, 24))
        seconds = (1000000000 * seconds + nanoseconds) / 1000000000
>       t = DateTime.combine(UNIX_EPOCH_DATE_ORDINAL + days, Time(hours, minutes, seconds))

../../venv/lib/python3.7/site-packages/neo4j/v1/types/temporal.py:112: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'neotime.DateTime'>, date = 737191, time = neotime.Time(19, 20, 52.748800999)

    @classmethod
    def combine(cls, date, time):
>       assert isinstance(date, Date)
E       AssertionError

../../venv/lib/python3.7/site-packages/neotime/__init__.py:1229: AssertionError
```

Can confirm this is the problem
```python
from neomodel.contrib import SemiStructuredNode
from neomodel import(
    StringProperty,
    UniqueIdProperty,
    IntegerProperty,
    DateTimeProperty,
    BooleanProperty
)
from typing import Optional
from datetime import datetime
import pytz
from .utils.sentimentSetter import SentimentSetter
class ConductedSurvey(SemiStructuredNode):

    nodeId = UniqueIdProperty()
    addedOn = DateTimeProperty(default_now=True)
    updatedOn = DateTimeProperty()
    closedOn = DateTimeProperty(default_now=True)
    status = StringProperty(
                            default="active", 
                            choices={
                                "closed": "closed",
                                "active": "active",
                                "abandoned": "abandoned"
                                }
                            )
    sentimentSet = BooleanProperty(default= False)
    def pre_save(self):
        if self.updatedOn is None:
            self.updatedOn = self.addedOn
        else:
            self.updatedOn = datetime.utcnow().replace(tzinfo=pytz.utc)
        if self.sentimentSet is False:
            SentimentSetter.setSentimentVariables(self)

    def set_closedOn(self, dt: Optional[datetime] = None) -> None:
        if dt is None:
            self.closedOn = datetime.utcnow().replace(tzinfo=pytz.utc)
        else:
            self.closedOn = dt.replace(tzinfo=pytz.utc)
```
When specifying the closedOn field in the definitions all the tests run as expected. Not sure if this is a bug or there should be a specific way to add a datetime field on a SemiStructuredNode

**Comment by aanastasiou** [comment] 2019-05-12 21:02
Hi, thanks for letting us know about this. Can I please ask what is the motivation that guides the structure of these models? What is it that you are trying to achieve? Why, for example, use a `SemiStructured` node and not a `StructuredNode` with an optional field?

Also, can you please strip out all extraneous information and provide the most elementary example that shows this error condition? If you can replicate it with a minimal script it would be even better (not necessarily run through the test infrastructure).

**Comment by Moro-Code** [comment] 2019-05-13 04:50
Hello, sorry if I added too much info. The reason I want a SemiStructured node is to be able to attach metadata to a particular node. Here is some minimal steps to reproduce this error 

```python 
# assume the config for neomodel has been set and labels have been installed
from neomodel.contrib import SemiStructuredNode
from neomodel import UniqueIdProperty
from neomodel import db
from datetime import datetime 
import pytz

class SomeNode(SemiStructuredNode):
       nodeId = UniqueIdProperty

with db.transaction:
    new_node = SomeNode()
    new_node.some_date = datetime.utcnow().replace(tzinfo=pytz.utc)
    new_node.save()
```

This code will never complete. 

Let me know if this helps or you need more info

**Comment by aanastasiou** [comment] 2019-05-13 16:47
@Moro-Code I can confirm that this test completes successfully on my end... And realise that this can be frustrating but, this is where we are...

It would definitely be worth checking your Neo4j logs.

**Comment by Moro-Code** [comment] 2019-05-13 17:13
Oh I'm sure it's something on my end but it's very very strange. This is the error I'm getting

```bash
cls = <class 'neotime.DateTime'>, date = 737192, time = neotime.Time(17, 11, 0.755438)

    @classmethod
    def combine(cls, date, time):
>       assert isinstance(date, Date)
E       AssertionError

../../survista-venv/lib/python3.7/site-packages/neotime/__init__.py:1229: AssertionError
```

Seems to be an issue with neotime but at this point I'm not sure anymore

**Comment by aanastasiou** [comment] 2019-05-15 16:44
@Moro-Code is it possible to construct a minimal demo case that fails like this?

It seems to be in the initialisation of a type that expects `Date` but receives `DateTime` (?) Maybe something to do with the time zone replacement ?

All the best

**Comment by Moro-Code** [comment] 2019-05-15 19:49
@aanastasiou I think I may have figure out a possible fix. Had a look in the documentation and I will set this in the config and let you know
```python 
config.FORCE_TIMEZONE = True  # default False
```

**Comment by aanastasiou** [comment] 2019-05-19 16:39
@Moro-Code Did this work? Is there anything we could perhaps add to the documentation about it (?)

**Comment by Moro-Code** [comment] 2019-05-20 23:44
@aanastasiou woops forgot to update you ! Surprisingly no, not sure what is going on at this point. All I know is somewhere in the driver an assertion is made to check whether the object is a date object as shown in. 

> Oh I'm sure it's something on my end but it's very very strange. This is the error I'm getting
> 
> ```shell
> cls = <class 'neotime.DateTime'>, date = 737192, time = neotime.Time(17, 11, 0.755438)
> 
>     @classmethod
>     def combine(cls, date, time):
> >       assert isinstance(date, Date)
> E       AssertionError
> 
> ../../survista-venv/lib/python3.7/site-packages/neotime/__init__.py:1229: AssertionError
> ```
> 
> Seems to be an issue with neotime but at this point I'm not sure anymore

**Comment by aanastasiou** [comment] 2019-05-23 06:31
@Moro-Code ok, no worries. I will close this for the moment but give it an update if you find out more later on (?)

All the best

**Closed by aanastasiou** 2019-05-23 06:31 UTC
