### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by marcosmoyano** [neo4j-contrib/neomodel#658] opened 2023-01-31 16:17 UTC
There are some important fixes in master that are not present in the latest release. I've encountered #551 and #555 in the past week to name a couple. Issues for which fixes have been made and are available in master.

On top of that, the latest release seems too long ago. What's stopping it from moving forward?

**Comment by mariusconjeaud** [comment] 2023-02-01 09:29
Please read here #653 

As for the fixes not in a release, let's see that with the main maintainers (I am new to this)

**Comment by mariusconjeaud** [comment] 2023-02-01 09:55
Duplicate of #653

**Comment by mariusconjeaud** [comment] 2023-02-01 09:55
Closing to group all discussions about the evolution of neomodel in #653

**Closed by mariusconjeaud** 2023-02-01 09:55 UTC
